export const SIGNUP_USER = "SIGNUP_USER";
export const SIGNIN_USER = "SIGNIN_USER";
export const SIGNEDIN_USER = "SIGNEDIN_USER";
export const SIGNOUT_USER = "SIGNOUT_USER";
export const SIGNEDOUT_USER = "SIGNEDOUT_USER";
export const FORGOTPASS_USER = "FORGOTPASS_USER";
export const SIGNINWITHGOOGLE = "SIGNINWITHGOOGLE";

export const SET_ALERT = "SET_ALERT";
export const RESET_ALERT = "RESET_ALERT";

export const ADD_CATEGORY = "ADD_CATEGORY";
export const GET_CATEGORY = "GET_CATEGORY";
export const UPDATE_CATEGORY = "UPDATE_CATEGORY";
export const DETETE_CATEGORY = "DETETE_CATEGORY";
export const ERROR_CATEGORY = "ERROR_CATEGORY";

export const ADD_PRODUCTS = "ADD_PRODUCTS";
export const GET_PRODUCTS = "GET_PRODUCTS";
export const UPDATE_PRODUCTS = "UPDATE_PRODUCTS";
export const DETETE_PRODUCTS = "DETETE_PRODUCTS";
export const ERROR_PRODUCTS = "ERROR_PRODUCTS";

export const INCREMENT_COUNTER = "INCREMENT_COUNTER";
export const DECREMENT_COUNTER = "DECREMENT_COUNTER";

export const ADD_CART = "ADD_CART";
export const GET_CART = "GET_CART";
export const DETELE_CART = "DELETE_CART";